"""add missing tables

Revision ID: 761d37f00986
Revises: ebd5cb470491
Create Date: 2026-08-10 20:53:32.568680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761d37f00986'
down_revision: Union[str, None] = 'ebd5cb470491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('cantidad_planificada', sa.Float(), nullable=True),
    sa.Column('unidad_cantidad', sa.String(length=20), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('completada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cantidad_real', sa.Float(), nullable=True),
    sa.Column('duracion_real', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('titulo_extra', sa.String(length=200), nullable=True),
    sa.Column('unidad_extra', sa.String(length=20), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('registrado_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas_produccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('productos_catalogo', sa.Column('receta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos_catalogo', 'recetas', ['receta_id'], ['id'])
    op.add_column('productos_congelados', sa.Column('receta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos_congelados', 'recetas', ['receta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos_congelados', type_='foreignkey')
    op.drop_column('productos_congelados', 'receta_id')
    op.drop_constraint(None, 'productos_catalogo', type_='foreignkey')
    op.drop_column('productos_catalogo', 'receta_id')
    op.drop_table('registros_produccion')
    op.drop_table('tareas_produccion')
    # ### end Alembic commands ###
