"""add producto_congelado_id to tareas

Revision ID: a73e99ac1304
Revises: d3c42abb0c15
Create Date: 2026-08-12 13:22:44.775573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73e99ac1304'
down_revision: Union[str, None] = 'd3c42abb0c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas_produccion', sa.Column('producto_congelado_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tareas_produccion', 'productos_congelados', ['producto_congelado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tareas_produccion', type_='foreignkey')
    op.drop_column('tareas_produccion', 'producto_congelado_id')
    # ### end Alembic commands ###
