"""initial models

Revision ID: b1785ae637b5
Revises: 
Create Date: 2026-08-10 14:54:08.926695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1785ae637b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('margen_objetivo', sa.Float(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('allowed', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'module', 'action', name='uq_permission')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pin_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('unidad_compra', sa.String(length=20), nullable=False),
    sa.Column('cantidad_compra', sa.Float(), nullable=False),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.Column('unidad_uso', sa.String(length=20), nullable=False),
    sa.Column('merma_porcentaje', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('porciones_por_lote', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('es_subreceta', sa.Boolean(), nullable=False),
    sa.Column('unidad_rendimiento', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('precio_anterior', sa.Float(), nullable=False),
    sa.Column('precio_nuevo', sa.Float(), nullable=False),
    sa.Column('fecha_cambio', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=True),
    sa.Column('subreceta_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['subreceta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precios_competencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('competidor_nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precios_competencia')
    op.drop_table('lineas_receta')
    op.drop_table('historial_precios')
    op.drop_table('recetas')
    op.drop_table('ingredientes')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
