"""add movimientos_stock table

Revision ID: c0ff3ba4307e
Revises: 761d37f00986
Create Date: 2026-08-10 23:24:37.454198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ff3ba4307e'
down_revision: Union[str, None] = '761d37f00986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_stock', sa.String(length=20), nullable=False),
    sa.Column('referencia_producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=30), nullable=False),
    sa.Column('referencia_origen', sa.String(length=100), nullable=True),
    sa.Column('saldo_despues', sa.Float(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('registrado_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_stock')
    # ### end Alembic commands ###
