"""add nivel padre to productos_congelados

Revision ID: d3c42abb0c15
Revises: c0ff3ba4307e
Create Date: 2026-08-12 00:13:34.617242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c42abb0c15'
down_revision: Union[str, None] = 'c0ff3ba4307e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos_congelados', sa.Column('nivel', sa.String(length=20), server_default='terminado', nullable=False))
    op.add_column('productos_congelados', sa.Column('producto_padre_id', sa.Integer(), nullable=True))
    op.add_column('productos_congelados', sa.Column('cantidad_por_padre', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'productos_congelados', 'productos_congelados', ['producto_padre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos_congelados', type_='foreignkey')
    op.drop_column('productos_congelados', 'cantidad_por_padre')
    op.drop_column('productos_congelados', 'producto_padre_id')
    op.drop_column('productos_congelados', 'nivel')
    # ### end Alembic commands ###
