"""add all remaining modules

Revision ID: ebd5cb470491
Revises: b1785ae637b5
Create Date: 2026-08-10 15:24:43.665719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd5cb470491'
down_revision: Union[str, None] = 'b1785ae637b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_b2b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('dia_entrega_preferido', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frigorificos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('disponible', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_congelados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('default_qty', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocolo_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_type', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('task_name', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('lead_time_dias', sa.Integer(), nullable=False),
    sa.Column('ciclo_pedido_dias', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('entregas_b2b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_b2b_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_b2b_id'], ['clientes_b2b.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas_temperatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frigorifico_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_alert', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.ForeignKeyConstraint(['frigorifico_id'], ['frigorificos.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frigorifico_id', 'target_date', 'shift', name='uq_lectura_temperatura')
    )
    op.create_table('logs_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=False),
    sa.Column('planned_qty', sa.Float(), nullable=True),
    sa.Column('actual_qty', sa.Float(), nullable=True),
    sa.Column('duration_minutes_machine', sa.Integer(), nullable=True),
    sa.Column('duration_minutes_human', sa.Integer(), nullable=True),
    sa.Column('is_unplanned', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_produccion.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'target_date', name='uq_log_produccion')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_recurrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('dia_entrega', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planes_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('planned_qty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_produccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'week_number', 'day_of_week', name='uq_plan_produccion')
    )
    op.create_table('protocolo_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('completed_by', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=False),
    sa.Column('target_period', sa.String(length=10), nullable=True),
    sa.Column('is_satisfactory', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['protocolo_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'target_date', name='uq_protocolo_completion')
    )
    op.create_table('stock_congelado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_congelado_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha_entrada', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['producto_congelado_id'], ['productos_congelados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_entrega_b2b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas_b2b.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_catalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_pedida', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('cantidad_recibida', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_pedido_recurrente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_recurrente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_default', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_recurrente_id'], ['pedidos_recurrentes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_catalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mermas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('nombre_libre', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('ubicacion', sa.String(length=10), nullable=True),
    sa.Column('coste_unitario', sa.Float(), nullable=False),
    sa.Column('coste_total', sa.Float(), nullable=False),
    sa.Column('registered_by', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('pedido_recurrente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['pedido_recurrente_id'], ['pedidos_recurrentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precios_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_por_unidad', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_pedido_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_cliente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario_snapshot', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_cliente_id'], ['pedidos_clientes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_catalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas_pedido_cliente')
    op.drop_table('precios_proveedor')
    op.drop_table('pedidos_clientes')
    op.drop_table('mermas')
    op.drop_table('lineas_pedido_recurrente')
    op.drop_table('lineas_pedido')
    op.drop_table('lineas_entrega_b2b')
    op.drop_table('inventario_registros')
    op.drop_table('stock_congelado')
    op.drop_table('protocolo_completions')
    op.drop_table('planes_produccion')
    op.drop_table('pedidos_recurrentes')
    op.drop_table('pedidos')
    op.drop_table('logs_produccion')
    op.drop_table('lecturas_temperatura')
    op.drop_table('entregas_b2b')
    op.drop_table('proveedores')
    op.drop_table('protocolo_templates')
    op.drop_table('productos_produccion')
    op.drop_table('productos_congelados')
    op.drop_table('productos_catalogo')
    op.drop_table('frigorificos')
    op.drop_table('clientes_b2b')
    # ### end Alembic commands ###
